### ISSUE TITLE
Resource Reload Failed

### ISSUE THREAD

**Issue by rtaha183** [MehVahdJukaar/polytone#55] opened 2024-06-21 14:41 UTC
Ever since I downloaded the mod, every time I try to load up my resource pack, it shows "Resource Reload Failed" on the top right. It works without the mod, but doesn't with the mod itself. The resource pack I'm using is Lively Default (attached). Please help.
[Lively Default 1.21.zip](https://github.com/user-attachments/files/15929048/Lively.Default.1.21.zip)

**Comment by XCraft810** [comment] 2024-06-21 14:42
![image](https://github.com/MehVahdJukaar/polytone/assets/67998032/c397dfd6-9f63-4546-9e02-4f593bce78cd)
these are the other mods i have installed as well

**Comment by rtaha183** [comment] 2024-06-21 16:17
It turns out it was because of the water colormap files... Removed those and it started working fine... Is there any possible way that the water colormap could work though???

**Comment by MehVahdJukaar** [comment] 2024-06-21 16:31
its probably wrong. latest.log will say why, all errors this mod produces are always in there. It will always reject stuff that is wrong instead of ignoring it such that errors can be found

**Comment by rtaha183** [comment] 2024-06-21 17:51
could you help me find where it could be (i'm sorry i'm pretty new to all this😭)

**Comment by rtaha183** [comment] 2024-06-21 18:06
"Could not resolve explicit texture at location minecraft:underwater.png. Skipping"
"Could not find any colormap texture .png associated with path minecraft:underwater"
"Could not find any colormap texture .png associated with path minecraft:underwater"

This is what it says

**Comment by rtaha183** [comment] 2024-06-21 18:11
ok so from what i understand is that the underwater file is the problem

**Comment by MehVahdJukaar** [comment] 2024-06-22 05:35
Send your pack or that section specifically

**Comment by Madis0** [comment] 2024-06-27 16:33
Here are logs using only Polytone 1.21-2.1.0 and Fabric API 0.100.4+1.21. 

I am attempting to activate the following resource packs: Lively Default (as linked in OP), [BetterVanillaBuilding v2.98.1](https://www.curseforge.com/minecraft/texture-packs/bettervanillabuilding/files/5428974), [Barely Default v1.13.8 by Mickey Joe](https://www.curseforge.com/minecraft/texture-packs/mickey-joes-relatively-improved-default/files/5442918), [New Default+ v1.75](https://www.curseforge.com/minecraft/texture-packs/newdefaultplus/files/5388649)

[latest.log](https://github.com/user-attachments/files/16018210/latest.log)

The following common errors can be observed:

Colormap errors
```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Could not find any colormap texture .png associated with path minecraft:custom/dirt
```

Font errors
```
[18:26:03] [Worker-Main-6/WARN]: Failed to load builder (patchouli:unicode_font: builder #249 from pack file/NewDefault+v1.75[MC1.20-1.20.4].zip), rejecting
java.io.FileNotFoundException: minecraft:textures/font/symbol_smp6.png
```

**Comment by MehVahdJukaar** [comment] 2024-06-27 17:19
This means something in them is invalid. Like that "custom/dir"  texture which I assume doesn't have a file associated will by default target the block at its own name so Minecraft:custom/dirt which doesn't exist. It needs either an valid implicit target or an explicit target defined in its JSON. The errors below are from patchouli

**Comment by Madis0** [comment] 2024-06-27 18:07
> This means something in them is invalid. Like that "custom/dir" texture which I assume doesn't have a file associated will by default target the block at its own name so Minecraft:custom/dirt which doesn't exist. It needs either an valid implicit target or an explicit target defined in its JSON. 

That sounds plausible, and it is what I initially thought too. However, it is possible to successfully load these packs in Polytone 1.20.6-1.18.12: [latest.log](https://github.com/user-attachments/files/16019196/latest.log)

In later versions of Polytone for 1.20.6, the same issue will occur, so it still looks like a regression.

**Comment by CamperSamu** [comment] 2024-07-11 21:58
I compiled a quick and dirty (and unsafe) version that has the `strict` check disabled in the colormap texture loading method, (`tryAcceptingTexture`) that also adds logging for the parameters in said method while preserving the stacktrace log.
I tested it with BetterThanVanilla on Fabric.

https://github.com/CamperSamu/polytone/releases/tag/1.21-2.1.1-patch


this is my stacktrace from loading the resourcepack:
```verilog
[23:48:22] [Render thread/INFO]: [STDOUT]: selectedTexture = null
[23:48:22] [Render thread/INFO]: [STDOUT]: textureLoc = minecraft:color
[23:48:22] [Render thread/INFO]: [STDOUT]: colormap = net.mehvahdjukaar.polytone.colormap.Colormap@7418bde3
[23:48:22] [Render thread/INFO]: [STDOUT]: usedTexture = []
[23:48:22] [Render thread/INFO]: [STDOUT]: strict = true
[23:48:22] [Render thread/INFO]: [STDERR]: java.lang.IllegalStateException: Could not find any colormap texture .png associated with path minecraft:color
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.mehvahdjukaar.polytone.colormap.ColormapsManager.tryAcceptingTexture(ColormapsManager.java:182)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.mehvahdjukaar.polytone.colormap.ColormapsManager.tryAcceptingTextureGroup(ColormapsManager.java:115)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.mehvahdjukaar.polytone.colormap.ColormapsManager.tryAcceptingTextureGroup(ColormapsManager.java:106)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.mehvahdjukaar.polytone.block.BlockPropertiesManager.process(BlockPropertiesManager.java:118)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.mehvahdjukaar.polytone.block.BlockPropertiesManager.process(BlockPropertiesManager.java:27)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.mehvahdjukaar.polytone.utils.CompoundReloader.processTyped(CompoundReloader.java:51)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.mehvahdjukaar.polytone.utils.CompoundReloader.apply(CompoundReloader.java:40)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.mehvahdjukaar.polytone.utils.CompoundReloader.method_18788(CompoundReloader.java:13)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4080.method_18790(class_4080.java:13)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4014.method_18365(class_4014.java:69)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:162)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:136)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:121)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1240)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:882)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:256)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[23:48:22] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[23:48:22] [Render thread/ERROR]: Found Polytone file minecraft:color with no valid implicit target and no explicit targets from registry Registry[ResourceKey[minecraft:root / minecraft:block] (Stable)]
```

**Comment by DangerMage** [comment] 2024-07-16 16:32
Any chance this will be fixed? I too am having this issue

**Comment by Tisawesomeness** [comment] 2024-08-14 17:45
> > This means something in them is invalid. Like that "custom/dir" texture which I assume doesn't have a file associated will by default target the block at its own name so Minecraft:custom/dirt which doesn't exist. It needs either an valid implicit target or an explicit target defined in its JSON.
> 
> That sounds plausible, and it is what I initially thought too. However, it is possible to successfully load (1.20.6 versions of) these packs in Polytone 1.20.6-1.18.12: [latest.log](https://github.com/user-attachments/files/16019196/latest.log)
> 
> In later versions of Polytone for 1.20.6, the same issue will occur, so it still looks like a regression.

The colormaps in the packs **are** invalid (see the [optifine docs](https://optifine.readthedocs.io/colormaps.html#format) for details):

In Lively Default, `assets/minecraft/optifine/colormap/underwater.properties` contains `blocks=underwater`, applying the colormap to the `minecraft:underwater` block which doesn't exist.

In BetterVanillaBuilding, `assets/minecraft/optifine/colormap/color.properties` has no `blocks` property, so it defaults to the `minecraft:color` block which doesn't exist.

Previous Polytone versions gracefully fail the block registry lookup and allow the rest of the pack to load, while newer versions throw an exception and cause the entire pack to fail.
```
# old
Found Polytone file minecraft:color with no valid implicit target and no explicit targets from registry Registry[ResourceKey[minecraft:root / minecraft:block] (Stable)]

# new
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Could not find any colormap texture .png associated with path minecraft:color
```

**Comment by Madis0** [comment] 2024-08-14 17:57
Fair enough, but why was it necessary to cause the entire pack to fail?

**Comment by MehVahdJukaar** [comment] 2024-08-14 19:00
Because if something is wrong it should fail. That's how one can avoid having incorrect stuff

**Comment by Tisawesomeness** [comment] 2024-08-14 20:33
The vanilla game does not fail loading the entire resource pack when one small part is invalid. Only the incorrect part fails to load with a warning informing the pack developer on how to fix it. This makes sense because resource packs can't cause permanent consequences in your world, unlike data packs where errors are less tolerated.

If you want the mod to deny loading the entire resource pack anyway, this issue should be closed as "invalid" or "wontfix".

**Comment by MehVahdJukaar** [comment] 2024-08-14 22:15
Because pack stuff is easier to write and manage. Datapack stuff is however much harder and thus much more error prone hence why it is not lenient. Polytone content is much more akin to a usual datpack than resource pack. Making stuff not load makes people will give a clear error message and popup saying where and why it failed rather that loading anyways a broken pack leaving people wonder why certain features don't work , inevitably getting frustrated because no apparent feedback and blaming the mod

**Comment by MehVahdJukaar** [comment] 2024-08-14 22:16
The issue above is a clear example as to why this kind of behaviour is preferred. Had that pack author used a mod with strict loading such an error would have never slipped in production

**Comment by Madis0** [comment] 2024-08-15 05:10
The problem is that this approach hurts users and Polytone more than it helps creators. 

- Users usually don't know how to read and fix crashes
- Users are likely fine with using a broken pack, as long as it otherwise works 
- Creators are not as likely to test on Polytone if they only use OptiFine features 

So, what if you make it crash only for _Polytone-exclusive_ features and log for OptiFine-compatible ones?

**Comment by notadev01** [comment] 2024-10-03 04:42
This is a weird hill to die on. Can't there be at least an option to load it anyway? I'd rather play the resource pack with a few missing features than not play it at all. The fact that this error completely resets the resource pack order doesn't help either. This also blocks people from using older packs as well.

**Comment by MR-CHOO** [comment] 2024-11-05 16:03
The whole issue here is the resourcepack developers fault, they’re formatting and developing the pack incorrectly. It’s not a bug with polytone, and can easily be fixed from the developers end. Though most large packs have severe loading errors with their files that aren’t skipped by polytone but are by optifine. Honestly it’s just something the pack devs are going to have to fix.

**Closed** 2024-11-05 17:25 UTC

**Comment by MR-CHOO** [comment] 2024-11-05 17:37
Also, just to mention, it's really easy for the pack devs to fix. I've personally fixed packs like reimagined or the other ones mentioned in a matter of minutes.
